// Candidate OS schema snapshot generated from the canonical AfrIA Recruit Supabase project on 2026-08-22.
// Scoped to tables consumed by apps/afria-recruit; regenerate when the live schema changes.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
type CandidateRow={created_at:string;current_country_code:string|null;embedding_model:string|null;home_country_code:string|null;id:string;professional_title:string|null;profile_embedding:string|null;profile_status:string;public_code:string;scope:string;source_channel:string;summary:string|null;updated_at:string;user_id:string;verification_summary_status:string;visibility:string;years_experience:number|null};
type ExperienceRow={candidate_id:string;claim_status:string;country_code:string|null;created_at:string;description:string|null;end_date:string|null;id:string;is_current:boolean;occupation_id:string|null;organization_name:string;sector_id:string|null;source_document_id:string|null;start_date:string|null;title:string};
type EducationRow={candidate_id:string;claim_status:string;completion_date:string|null;country_code:string|null;created_at:string;field_of_study:string|null;id:string;institution_name:string;qualification:string;source_document_id:string|null;start_date:string|null};
type SkillRow={candidate_id:string;created_at:string;evidence_status:string;last_used_year:number|null;proficiency:string;skill_id:string;years_experience:number|null};
type LanguageRow={candidate_id:string;evidence_status:string;language_code:string;level:string};
type CertificationRow={candidate_id:string;claim_status:string;created_at:string;credential_reference:string|null;expires_at:string|null;id:string;issued_at:string|null;issuer:string|null;name:string;source_document_id:string|null};
type PreferencesRow={available_from:string|null;candidate_id:string;compensation_currency:string|null;contract_types:string[];minimum_compensation:number|null;preferred_country_codes:string[];preferred_work_modes:string[];updated_at:string;willing_field_rotation:boolean;willing_to_relocate:boolean;work_authorization_summary:string|null};
type VerificationRow={candidate_id:string;claim_reference:string|null;claim_type:string;created_at:string;evidence_hash:string|null;expires_at:string|null;id:string;notes:string|null;source_type:string|null;source_uri:string|null;status:string;updated_at:string;verified_at:string|null;verified_by:string|null};
type DocumentRow={candidate_id:string;document_type:string;id:string;mime_type:string|null;parsed_claim_status:string;parsed_data:Json;parsing_status:string;sha256:string|null;storage_bucket:string;storage_path:string;uploaded_at:string};
type SkillCatalogRow={active:boolean;category:string;code:string;created_at:string;embedding:string|null;embedding_model:string|null;id:string;name_en:string;name_fr:string};
type AiDecisionRow={candidate_id:string|null;confidence:number|null;created_at:string;decision_status:string;decision_type:string;human_review_required:boolean;id:string;input_hash:string;job_id:string|null;model_id:string;model_provider:string;output:Json;prompt_version:string};
type JobRow={id:string;organization_id:string;title:string;description:string|null;work_mode:string;contract_type:string;seniority:string|null;openings:number;published_at:string|null;application_deadline:string|null;source_url:string|null;status:string;provenance_status:string;raw_payload:Json;created_at:string;updated_at:string};
type JobSkillRow={job_id:string;skill_id:string;importance:number;required:boolean;minimum_years:number|null};
type JobLanguageRow={job_id:string;language_code:string;minimum_level:string;required:boolean};
type JobLocationRow={id:string;job_id:string;country_code:string;city:string|null;is_primary:boolean;relocation_supported:boolean;visa_sponsorship_status:string};
type HumanReviewRow={id:string;ai_decision_id:string|null;match_id:string|null;reviewer_id:string;outcome:string;rationale:string;created_at:string};
type ConsentRow={id:string;candidate_id:string;organization_id:string|null;job_id:string|null;purpose:string;data_categories:string[];policy_version:string;status:string;granted_at:string;expires_at:string|null;withdrawn_at:string|null;evidence:Json;created_at:string};
type InterviewRow={id:string;candidate_id:string;job_id:string|null;assessment_attempt_id:string|null;consent_id:string;status:string;model_provider:string;model_id:string;prompt_version:string;started_at:string|null;completed_at:string|null;recording_storage_path:string|null;transcript_storage_path:string|null;evaluation_status:string;created_at:string};
type ApplicationRow={id:string;candidate_id:string;job_id:string;consent_id:string|null;status:string;source:string;applied_at:string|null;created_at:string;updated_at:string};
type ApplicationEventRow={id:string;application_id:string;from_status:string|null;to_status:string;actor_user_id:string|null;reason:string|null;metadata:Json;created_at:string};
type TableDef<Row>={Row:Row;Insert:Partial<Row>;Update:Partial<Row>;Relationships:[]};
export type Database={public:{Tables:{candidates:TableDef<CandidateRow>;candidate_experiences:TableDef<ExperienceRow>;candidate_educations:TableDef<EducationRow>;candidate_skills:TableDef<SkillRow>;candidate_languages:TableDef<LanguageRow>;candidate_certifications:TableDef<CertificationRow>;candidate_preferences:TableDef<PreferencesRow>;verifications:TableDef<VerificationRow>;candidate_documents:TableDef<DocumentRow>;skills:TableDef<SkillCatalogRow>;ai_decisions:TableDef<AiDecisionRow>;jobs:TableDef<JobRow>;job_skills:TableDef<JobSkillRow>;job_languages:TableDef<JobLanguageRow>;job_locations:TableDef<JobLocationRow>;human_reviews:TableDef<HumanReviewRow>;consents:TableDef<ConsentRow>;ai_interviews:TableDef<InterviewRow>;applications:TableDef<ApplicationRow>;application_events:TableDef<ApplicationEventRow>};Views:Record<string,never>;Functions:Record<string,never>;Enums:Record<string,never>;CompositeTypes:Record<string,never>}};
export type CandidateDbRow=CandidateRow;export type CandidateExperienceDbRow=ExperienceRow;export type CandidateEducationDbRow=EducationRow;export type CandidateSkillDbRow=SkillRow;export type CandidateLanguageDbRow=LanguageRow;export type CandidateCertificationDbRow=CertificationRow;export type CandidatePreferencesDbRow=PreferencesRow;export type CandidateVerificationDbRow=VerificationRow;export type CandidateDocumentDbRow=DocumentRow;export type AiDecisionDbRow=AiDecisionRow;
