export const dossierStates = [
  'DRAFT',
  'SUBMITTED',
  'RECEIVED',
  'UNDER_COMPLETENESS_REVIEW',
  'INCOMPLETE',
  'COMPLEMENT_REQUESTED',
  'ADMISSIBLE',
  'ASSIGNED',
  'UNDER_INSTRUCTION',
  'UNDER_ANALYSIS',
  'PENDING_HIERARCHICAL_VALIDATION',
  'DECISION_PREPARED',
  'DECIDED',
  'NOTIFIED',
  'CLOSED',
  'ARCHIVED',
] as const;

export type DossierState = (typeof dossierStates)[number];

export const allowedTransitions: Record<DossierState, readonly DossierState[]> = {
  DRAFT: ['SUBMITTED'],
  SUBMITTED: ['RECEIVED'],
  RECEIVED: ['UNDER_COMPLETENESS_REVIEW'],
  UNDER_COMPLETENESS_REVIEW: ['INCOMPLETE', 'ADMISSIBLE'],
  INCOMPLETE: ['COMPLEMENT_REQUESTED'],
  COMPLEMENT_REQUESTED: ['UNDER_COMPLETENESS_REVIEW'],
  ADMISSIBLE: ['ASSIGNED'],
  ASSIGNED: ['UNDER_INSTRUCTION'],
  UNDER_INSTRUCTION: ['UNDER_ANALYSIS', 'COMPLEMENT_REQUESTED'],
  UNDER_ANALYSIS: ['COMPLEMENT_REQUESTED', 'PENDING_HIERARCHICAL_VALIDATION'],
  PENDING_HIERARCHICAL_VALIDATION: ['DECISION_PREPARED', 'UNDER_ANALYSIS'],
  DECISION_PREPARED: ['DECIDED'],
  DECIDED: ['NOTIFIED'],
  NOTIFIED: ['CLOSED'],
  CLOSED: ['ARCHIVED'],
  ARCHIVED: [],
};

export function canTransition(from: DossierState, to: DossierState): boolean {
  return allowedTransitions[from].includes(to);
}
