services:
  - type: web
    name: afria-payswitch-runtime
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PAYSWITCH_API_KEY
        sync: false
      - key: PAYSWITCH_CONSOLE_USER
        sync: false
      - key: PAYSWITCH_CONSOLE_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
