from __future__ import annotations

from typing import Protocol, runtime_checkable

from app.domain.models import TelemetryPoint


@runtime_checkable
class ReadOnlyAdapter(Protocol):
    def connect(self) -> None: ...
    def health(self) -> dict[str, str]: ...
    def discover_readable_points(self) -> list[dict[str, str]]: ...
    def read_batch(self) -> list[TelemetryPoint]: ...
    def disconnect(self) -> None: ...
